
name: flask-app-ci

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: flask-app

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.Docker_USERNAME }}
          password: ${{ secrets.Docker_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker buildx build \
             --platform linux/arm64 \
             -t ${{ secrets.Docker_USERNAME }}/flask-app:latest \
             --push .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.Docker_USERNAME }}/flask-app:latest

      - name: Deploy to Azure
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.azure_HOST }}
          username: ${{ secrets.azure_USER }}
          key: ${{ secrets.azure_SSH_KEY }}
          script: |
            docker pull ${{ secrets.Docker_USERNAME }}/flask-app:latest

            docker stop flask-app || true
            docker rm flask-app || true

            docker run -d \
              -p 80:5000 \
              --name flask-app \
              --restart unless-stopped \
              ${{ secrets.Docker_USERNAME }}/flask-app:latest

            docker image prune -f

  
